config/routes.rb
Rails.application.routes.draw do

  devise_for :users, {
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations'
    }
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get '/.well-known/pki-validation/88744B73F9335042F17349D9AD3271A7.txt',
    to: 'application#http_validate_ssl'

  root to: "podcasts#index"

  resources :posts

  resources :podcasts

  get "/admin",
    to: redirect( "/users/sign_in" )

  get "/rss/podcasts", to: redirect("http://taoofcomedy.libsyn.com/rss")
    # to: 'podcasts#index',
    # as: :podcasts_rss,
    # defaults: { format: 'rss' }

  get "/news",
    to: "pages#news",
    as: :news_path

  get "/about",
    to: "pages#about",
    as: :about_path

  get "/donate",
    to: "pages#donate",
    as: :donate_path

  post "/donate/process",
    to: 'pages#donate_process',
    as: :donate_process

  get "/photos",
    to: "pages#photos",
    as: :photos_path

  get "/videos",
    to: "pages#videos",
    as: :videos_path

  get "/contact",
    to: "pages#contact",
    as: :contact_path

  namespace :admin do
    resources :posts

    resources :podcasts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :main_image,
                    styles: {
                      large: "600x600>",
                      medium: "300x300>",
                      thumb: "100x100>"
                    },
                    default_url: "/images/:style/missing.png"
  has_attached_file :secondary_image,
                    styles: {
                      large: "600x600>",
                      medium: "300x300>",
                      thumb: "100x100>"
                    },
                    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :main_image,
                                    content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :secondary_image,
                                    content_type: /\Aimage\/.*\Z/

  validates :body,
          # :main_image,
            :published_date,
            :title,
            presence: true
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def index
    @posts = Post.all.order( "created_at DESC" )
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to(
        admin_posts_path,
        flash: {
          success: "You created the \"#{@post.title}\" post. "
        }
      )
    else
      errors = @post.errors.full_messages.join(", ")
      flash.now[:error] = "Something went wrong!\n"\
                          "Check these: #{errors}"
      render :new
    end
  end

  def show
    redirect_to(
      admin_edit_post_path( @post )
    )
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to(
        admin_posts_path,
        flash: {
          success: "You created the \"#{@post.title}\" post. "
        }
      )
    else
      errors = @post.errors.full_messages.join(", ")
      flash.now[:error] = "Something went wrong!\n"\
                          "Check these: #{errors}"
      render :edit
    end
  end

  private

  def find_post
    @post = Post.find( params[:id] )
  end

  def post_params
    params.require( :post ).permit(
      :body,
      :description,
      :published_date,
      :main_image,
      :secondary_image,
      :title,
      :visible
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order( "created_at DESC" )
  end

  def show
    @post = Post.find( params[:id] )
  end

end

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 pull-left">
      <h1 class="text-center">The Tao of Comedy</h1>
      <h2>Hosted by:</h2>
      <h2>Kelly MacLean</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% @posts.each do |post| %>
        <% if post.visible? %>
          <h3><%= link_to post.title, post_path( post.id ) %></h3>
          <br>
          <p><%= post.description %></p>
          <br>
          <p><%= post.published_date.strftime( "%m/%d/%y" ) %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "&larr; Back to Podcasts".html_safe, podcasts_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1><%= @post.title %></h1>
      <br>
      <p><%= @post.description %></p>
      <br>
      <p><%= @post.published_date %></p>
    </div>
  </div>
</div>