config/routes.rb
Rails.application.routes.draw do

  devise_for :users, {
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations'
    }
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  get '/.well-known/pki-validation/88744B73F9335042F17349D9AD3271A7.txt',
    to: 'application#http_validate_ssl'

  root to: "podcasts#index"

  resources :posts

  resources :podcasts

  get "/admin",
    to: redirect( "/users/sign_in" )

  get "/rss/podcasts", to: redirect("http://taoofcomedy.libsyn.com/rss")
    # to: 'podcasts#index',
    # as: :podcasts_rss,
    # defaults: { format: 'rss' }

  get "/news",
    to: "pages#news",
    as: :news_path

  get "/about",
    to: "pages#about",
    as: :about_path

  get "/donate",
    to: "pages#donate",
    as: :donate_path

  post "/donate/process",
    to: 'pages#donate_process',
    as: :donate_process

  get "/photos",
    to: "pages#photos",
    as: :photos_path

  get "/videos",
    to: "pages#videos",
    as: :videos_path

  get "/contact",
    to: "pages#contact",
    as: :contact_path

  namespace :admin do
    resources :posts

    resources :podcasts
  end

end

app/views/layouts/_admin_header.html.erb
<% if user_signed_in? && current_user.admin? %>
  <nav
    class="navbar admin-navbar navbar-default navbar-fixed-top"
    id="admin-navbar"
  >
    <div class="container-fluid">
      <div calss="navbar-header">
        <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#adminNav"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= admin_podcasts_path %>">
          Admin
        </a>
      </div>
      <div
        id="adminNav"
        class="collapse navbar-collapse"
      >
        <ul class="nav navbar-nav <%= 'pull-left' unless mobile_device? %>">
          <li><%= link_to "Homepage", root_path %></li>
          <li><%= link_to "Podcasts", admin_podcasts_path %></li>
          <li><%= link_to "Posts", admin_posts_path %></li>
          <li><%= link_to "Create a Podcast", new_admin_podcast_path %></li>
          <li><%= link_to "Create a Post", new_admin_post_path %></li>
          <% if post? %>
            <li><%= link_to "Edit Post", edit_admin_post_path( @post ) %></li>
          <% end %>
          <% if podcast? %>
            <li><%= link_to "Edit Podcast", edit_admin_podcast_path( @podcast ) %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav <%= 'pull-right' unless mobile_device? %>">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right" role="menu">
              <li>
                <%= link_to "Admin", admin_podcasts_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to(
                  "Sign Out",
                  destroy_user_session_path,
                  method: "delete"
                    )
                %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/_fb_metas.html.erb
<meta property="og:type" content="website" />
<meta property="fb:app_id" content="<%= ENV[ 'FACEBOOK_APP_ID' ] %>" />
<meta property="og:site_name" content="The Tao of Comedy" />
<% if post? %>
  <meta
    property="og:title"
    content="<%= @post.title + ' -- The Tao of Comedy' %>"
  />
  <meta property="og:description" content="<%=
    @post.description
  %>" />
  <meta property="og:image" content="<%=
    @post.main_image.url(:large)
  %>"/>
<% elsif podcast? %>
  <meta
    property="og:title"
    content="<%= @podcast.title + ' -- The Tao of Comedy' %>"
  />
  <meta property="og:description" content="<%=
    @podcast.description
  %>" />
  <meta property="og:image" content="<%=
    @podcast.main_image.url(:large)
  %>"/>
<% else %>
  <meta
    property="og:title"
    content="<%= 'The Tao of Comedy' %>"
  />
  <meta property="og:description" content="Kelly MacLean's podcast -- The Tao of Comedy" />
  <meta property="og:image" content="Need to put in image here."/>
<% end %>
<meta property="og:url" content="<%=
  '#{request.protocol}#{request.host_with_port}#{request.fullpath}'
%>" />

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% if value.present? %>
    <div class="alert alert-<%= key.to_s %> <%= 'alert-admin' if current_user %>">
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        Copyright Kelly MacLean ©<%= Time.now.year %>. All Rights Reserved.
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="navbar-product">
  <nav
    class="navbar <%=
      mobile_device? ? 'navbar-inverse navbar-fixed-top' : 'navbar-default'
    %>"
    style="margin-bottom: 0; <%=
      if mobile_device?
        current_user ? 'margin-top: 50px;' : 'margin-top: 0;'
      else
        'border-color: #fff;'
      end
    %>"
  >
    <div class="container-fluid">
      <div class="navbar-header">
        <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#taoPodNav"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div
        id="taoPodNav"
        class="collapse navbar-collapse"
      >
        <ul class="nav navbar-nav">
          <% unless params[:action] == "index" && params[:controller] == "podcasts" %>
            <li>
              <a class="navbar-link" href="/">Listen to Podcasts</a>
            </li>
          <% end %>
          <li>
            <a class="navbar-link" href="/about">About</a>
          </li>
          <li>
            <a class="navbar-link" href="/donate">Donate</a>
          </li>
          <li>
            <a class="navbar-link" href="/#amazon-portal">Amazon Portal</a>
          </li>
          <li>
            <a
              class="navbar-link"
              href="http://kellymacleancomedy.com/"
            >Kelly's Website</a>
          </li>
          <li>
            <a class="navbar-link"href="/photos">Photos</a>
          </li>
          <li>
            <a
              class="navbar-link"
              href="https://www.facebook.com/kellymacleancomedy/">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li>
            <a class="navbar-link" href="https://twitter.com/thekellymaclean">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li>
            <a
              class="navbar-link"
              href="https://itunes.apple.com/us/podcast/the-tao-of-comedy/id1115517397"
            ><i class="fa fa-music"></i></a>
          </li>
          <li>
            <a
              class="navbar-link"
              href="http://www.stitcher.com/s?fid=90579&refid=stpr">Stitcher</a>
          </li>
          <li>
            <a
              class="navbar-link"
              href="/contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_jplayer.html.erb
<div class="jplayer-wrapper">
  <div id="jquery_jplayer_<%= i %>" class="jp-jplayer"></div>
  <div id="jp_container_<%= i %>" class="jp-audio" role="application" aria-label="media player">
    <div class="jp-interface">
      <div class="jp-button jp-playpause-button">
        <button class="jp-play" role="button" tabindex="0">play</button>
      </div>
      <div class="jp-time-rail">
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-time-holder">
          <div class="pull-left jp-current-time" role="timer" aria-label="time">&nbsp;</div>
          <div class="pull-right jp-duration" role="timer" aria-label="duration">&nbsp;</div>
        </div>
      </div>
      <div class="jp-button jp-volume-button">
        <button class="jp-mute" role="button" tabindex="0">max volume</button>
      </div>
      <div class="jp-volume-bar">
        <div class="jp-volume-bar-value"></div>
      </div>
    </div>
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div><!-- .jp-audio -->
</div><!-- .demo-player -->

app/views/layouts/_social_js.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76414309-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Tao of Comedy</title>
    <link rel="icon" type="image/png" href="/assets/favicon.png">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- auto_discovery_link_tag(:rss, podcasts_rss_path) -->

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">

    <%= javascript_include_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js"></script>
    <%= render partial: "layouts/social_js" %>
  </head>

  <body>

    <div id="wrap">
      <%= render partial: "layouts/flash" %>
      <div id="main" style="<%= 'margin-top: 50px' if current_user %>">
        <%= render partial: "layouts/admin_header" %>

        <%= yield %>
      </div>
    </div>

    <%= render partial: "layouts/footer" %>
  </body>
</html>